# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lcc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('main_class_start', models.IntegerField(db_index=True)),
                ('sub_class_start', models.IntegerField(db_index=True)),
                ('main_class_end', models.IntegerField(db_index=True)),
                ('sub_class_end', models.IntegerField(db_index=True)),
                ('year', models.CharField(blank=True, max_length=6, null=True)),
                ('author', models.CharField(blank=True, max_length=10, null=True)),
                ('regal', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
