# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lcc',
            name='sub_class_end',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='lcc',
            name='sub_class_start',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
